AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  upload-handler

Sample SAM Template for upload-handler:

Globals:
  Function:
    Timeout: 30
  Api:
    BinaryMediaTypes: ['*~1*']
Resources:
  UploadFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: upload_handler/
      Handler: app.upload_handler
      Runtime: python3.7
      Events:
        Upload:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/v1/upload/{cpf}
            Method: post
ListFilesFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: upload_handler/
      Handler: app.get_files
      Runtime: python3.7
      Events:
        GetFiles:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/v1/upload/files
            Method: get
DownloadFileFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: upload_handler/
      Handler: app.download_file
      Runtime: python3.7
      Events:
        GetFile:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /api/v1/upload/file/{filename}
            Method: get
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  UploadApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  UploadFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt UploadFunction.Arn
  UploadFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt UploadFunctionRole.Arn